site_name: RingCentral Integrations Cookbook
site_url: https://github.com/grokify/ringcentral-integrations-cookbook
repo_url: https://github.com/grokify/ringcentral-integrations-cookbook.git
docs_dir: docs
theme: readthedocs
pages:
# Introduction:
- ['index.md', 'Introduction', 'RingCentral Integrations Cookbook']

## Integrations:
- ['integrations/manageengine/self_service_password_sms.md', 'Integrations', 'ManageEngine ADSelfService']
